name: .NET Build and Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      test_type:
        description: 'Which tests should run?'
        required: true
        type: choice
        options:
          - Unit
          - Api
          - All
        default: Unit

  schedule:
    # API tests: every day at 07:00 UTC
    - cron: '0 7 * * *'
    
    # API tests: every day at 20:00 Mexico City time
#    - cron: '0 20 * * *'
#      timezone: 'America/Mexico_City'
      
    # Unit tests: every day at 21:00 Mexico City time
 #   - cron: '0 21 * * *'
 #     timezone: 'America/Mexico_City'

jobs:
  build:

    runs-on: windows-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TestAutomation_CI_CD.sln

      - name: Build
        run: dotnet build TestAutomation_CI_CD.sln --configuration Release --no-restore
        
        
      - name: Upload failed test screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-screenshots
          path: '**/TestResults/Screenshots/**'
          if-no-files-found: ignore
        
        #run: dotnet test --filter "TestCategory=API"
      - name: Run API Tests
        env:
          BROWSER: ${{ inputs.browser }}
          HEADLESS: true
          
        if: |
          github.event_name == 'schedule' && github.event.schedule == '0 7 * * *' ||
          github.event_name == 'workflow_dispatch' && (inputs.test_type == 'Api' || inputs.test_type == 'All')
        run: dotnet test --filter "TestCategory=API" --configuration Release --no-build
 
      - name: Run Unit Tests
        if: |
          github.event_name == 'schedule' && github.event.schedule == '0 7 * * *' ||
          github.event_name == 'workflow_dispatch' && (inputs.test_type == 'Unit' || inputs.test_type == 'All')
        run: dotnet test --filter "TestCategory=Unit" --configuration Release --no-build
        



     # Manual: Unit
     # Manual: All
     # Schedule at 20:00
 #    - name: Run Unit Tests
 #      if: |
 #        github.event_name == 'schedule' && github.event.schedule == '0 20 * * *' ||
 #        github.event_name == 'workflow_dispatch' && (inputs.test_type == 'Unit' || inputs.test_type == 'All')
 #      run: dotnet test --filter "TestCategory=Unit" --configuration Release --no-build

    # Manual: API
    # Manual: All
    # Schedule at 07:00
#      - name: Run API Tests
#        if: |
#          github.event_name == 'schedule' && github.event.schedule == '0 21 * * *' ||
#          github.event_name == 'workflow_dispatch' && (inputs.test_type == 'Api' || inputs.test_type == 'All')
#        run: dotnet test --filter "TestCategory=API" --configuration Release --no-build