name: .NET Build and Test

on:
#  push:
#    branches:
#      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
    
      test_type:
        description: 'Which tests should run?'
        required: true
        type: choice
        options:
          - Unit
          - Api
          - All
        default: Unit
        
      browser:
        description: 'Browser to execute tests'
        required: true
        type: choice
        default: chrome
        options:
          - chrome
          - edge
          - firefox

  schedule:
    # API tests: every day at 07:00 UTC
    #- cron: '0 7 * * *'
    
    # API tests: every day at 20:00 Mexico City time
    - cron: '0 05 * * *'
      timezone: 'America/Mexico_City'
      
    # Unit tests: every day at 21:00 Mexico City time
    - cron: '0 06 * * *'
      timezone: 'America/Mexico_City'

jobs:
  build:

    runs-on: windows-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TestAutomation_CI_CD.sln

      - name: Build
        run: dotnet build TestAutomation_CI_CD.sln --configuration Release --no-restore

      - name: Run API Tests
        env:
          BROWSER: ${{ inputs.browser }}
          HEADLESS: true
          
        #run: dotnet test --filter "TestCategory=API"
        if: |
          github.event_name == 'schedule' && github.event.schedule == '0 05 * * *' ||
          github.event_name == 'workflow_dispatch' && (inputs.test_type == 'Api' || inputs.test_type == 'All')
        run: dotnet test --filter "TestCategory=API" --configuration Release --no-build
 
        #run: dotnet test --filter "TestCategory=Unit"
      - name: Run Unit Tests
        if: |
          github.event_name == 'schedule' && github.event.schedule == '0 06 * * *' ||
          github.event_name == 'workflow_dispatch' && (inputs.test_type == 'Unit' || inputs.test_type == 'All')
        run: dotnet test --filter "TestCategory=Unit" --configuration Release --no-build
        
        
      - name: Upload failed test screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-screenshots
          path: '**/TestResults/Screenshots/**'
          if-no-files-found: ignore

